exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - package.json
  - package-lock.json
  - script
  - src

remote_theme: marella/jekyll-theme-documentation

permalink: pretty
nav:
  - Введение:
    - Предисловие: 'content/introduction/introduction'
    - Примеры Java-online: 'content/introduction/examples-java-online'
    - Другие книги от O`Reilly: 'content/introduction/other-books-of-oreilly'
  - Глава 1. Основы Java:
    - Hello World: 'content/chapter-1/hello-world'
    - FizzBuzz: 'content/chapter-1/fizz-buzz'
  - Демонстрация:
    - Markdown: demos/markdown
    - Другая страница: demos/another-page
    - Оглавление: demos/toc
